# Generated by Django 4.1.5 on 2023-03-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='fees',
            field=models.IntegerField(default=0, verbose_name='Сборы'),
        ),
    ]
